{
 "title": "GO RUNTIME METRICS",
 "description": "Process status and runtime metrics published by Go Prometheus client.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" }
  ]
 },
 "panels": [
  {
   "title": "misc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC duration quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "go_gc_duration_seconds", "legendFormat": "{{quantile}}" }
     ]
    },
    {
     "title": "pointer deferences",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_memstats_lookups_total", "legendFormat": "Pointer dereferences" }
     ]
    }
   ]
  },
  {
   "title": "file descriptors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "open fds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "process_open_fds" }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "deriv(process_open_fds[$interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "goroutine stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Goroutines",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_goroutines" }
     ]
    },
    {
     "title": "OS Threads",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "go_threads" }
     ]
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "alloc bytes allocated",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_alloc_bytes", "legendFormat": "bytes allocated" }
     ]
    },
    {
     "title": "alloc bytes allocated - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes[$interval])",
       "legendFormat": "bytes allocated"
      }
     ]
    },
    {
     "title": "stack in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_stack_inuse_bytes", "legendFormat": "stack inuse" }
     ]
    },
    {
     "title": "stack in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes[$interval])",
       "legendFormat": "stack inuse"
      }
     ]
    },
    {
     "title": "heap in use - bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "go_memstats_heap_inuse_bytes", "legendFormat": "heap inuse" }
     ]
    },
    {
     "title": "heap in use - bytes - derivative",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes[$interval])",
       "legendFormat": "heap inuse"
      }
     ]
    },
    {
     "title": "total alloc bytes allocation rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(go_memstats_alloc_bytes_total[30s])",
       "legendFormat": "alloc rate"
      }
     ]
    }
   ]
  },
  {
   "title": "process memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "process resident memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "process_resident_memory_bytes", "legendFormat": "resident" }
     ]
    },
    {
     "title": "process resident memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes[$interval])",
       "legendFormat": "resident"
      }
     ]
    },
    {
     "title": "process virtual memory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      { "expr": "process_virtual_memory_bytes", "legendFormat": "virtual" }
     ]
    },
    {
     "title": "process virtual memory derivative",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "deriv(process_virtual_memory_bytes[$interval])",
       "legendFormat": "virtual"
      }
     ]
    }
   ]
  }
 ]
}